Description: First home task. A template for creating EC2 instance with security groups.

Parameters:
  EC2InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium

  ImageId:
    Description: EC2 instance image id
    Type: String
    Default: ami-0c2d06d50ce30b442

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType:
        Ref: EC2InstanceType

Outputs:
  PublicIp:
    Description: EC2Instance public IP
    Value: !GetAtt EC2Instance.PublicIp